"""change bucket and orders

Revision ID: b7d722bd8a35
Revises: e9ad78b97228
Create Date: 2024-12-22 17:58:48.020066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d722bd8a35'
down_revision: Union[str, None] = 'e9ad78b97228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('order_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_status', sa.Enum('CREATED', 'IS_PAID', 'IS_GOING_TO', 'IN_DELIVERY', 'DELIVERED', 'PRESENTED', 'CANCELED', name='orderstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'store_order_products', 'store_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_order_products', type_='foreignkey')
    op.drop_table('store_orders')
    # ### end Alembic commands ###
