"""change bucket and orders

Revision ID: e9ad78b97228
Revises: 83e2d7b73c87
Create Date: 2024-12-14 19:24:56.969239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ad78b97228'
down_revision: Union[str, None] = '83e2d7b73c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_bucket', sa.Column('product_count', sa.Integer(), nullable=False))
    op.add_column('store_bucket', sa.Column('product_size', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'store_bucket', ['id'])
    op.add_column('store_order_products', sa.Column('product_size', sa.Integer(), nullable=False))
    op.drop_column('store_order_products', 'product_name')
    op.drop_column('store_order_products', 'product_price')
    op.create_unique_constraint(None, 'store_products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_products', type_='unique')
    op.add_column('store_order_products', sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('store_order_products', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('store_order_products', 'product_size')
    op.drop_constraint(None, 'store_bucket', type_='unique')
    op.drop_column('store_bucket', 'product_size')
    op.drop_column('store_bucket', 'product_count')
    # ### end Alembic commands ###
